port_service_map = {
    1: 'TCP Port Service Multiplexer (TCPMUX)',
    5: 'Remote Job Entry (RJE)',
    7: 'Echo Protocol',
    18: 'Message Send Protocol (MSP)',
    20: 'FTP Data Transfer',
    21: 'FTP Control (Command)',
    22: 'SSH Remote Login Protocol',
    23: 'Telnet',
    25: 'Simple Mail Transfer Protocol (SMTP)',
    29: 'MSG ICP',
    37: 'Time Protocol',
    42: 'Host Name Server (Nameserv)',
    43: 'Whois Protocol',
    49: 'Login Host Protocol (Login)',
    53: 'Domain Name System (DNS)',
    67: 'Bootstrap Protocol (BOOTP) Server',
    68: 'Bootstrap Protocol (BOOTP) Client',
    69: 'Trivial File Transfer Protocol (TFTP)',
    70: 'Gopher Protocol',
    79: 'Finger Protocol',
    80: 'Hypertext Transfer Protocol (HTTP)',
    88: 'Kerberos',
    95: 'SUPDUP',
    101: 'NIC Host Name',
    105: 'CCSO Nameserver (Qi/Ph)',
    107: 'Remote Telnet Service',
    109: 'Post Office Protocol version 2 (POP2)',
    110: 'Post Office Protocol version 3 (POP3)',
    111: 'SUN Remote Procedure Call (RPC)',
    113: 'Ident',
    115: 'Simple File Transfer Protocol (SFTP)',
    117: 'UUCP Path Service',
    119: 'Network News Transfer Protocol (NNTP)',
    123: 'Network Time Protocol (NTP)',
    135: 'Microsoft RPC',
    137: 'NetBIOS Name Service',
    138: 'NetBIOS Datagram Service',
    139: 'NetBIOS Session Service',
    143: 'Internet Message Access Protocol (IMAP)',
    161: 'Simple Network Management Protocol (SNMP)',
    162: 'SNMP Trap',
    179: 'Border Gateway Protocol (BGP)',
    194: 'Internet Relay Chat (IRC)',
    201: 'AppleTalk Routing Maintenance',
    264: 'BGMP',
    318: 'TSP',
    381: 'HP OpenView',
    383: 'HP OpenView',
    389: 'Lightweight Directory Access Protocol (LDAP)',
    411: 'Direct Connect Hub',
    412: 'Direct Connect Client',
    443: 'HTTP Secure (HTTPS)',
    445: 'Microsoft-DS',
    464: 'Kerberos Change/Set Password',
    465: 'SMTP over SSL (SMTPS)',
    500: 'Internet Security Association and Key Management Protocol (ISAKMP)',
    512: 'exec',
    513: 'Login',
    514: 'Shell',
    515: 'Line Printer Daemon (LPD)',
    520: 'Routing Information Protocol (RIP)',
    521: 'Routing Information Protocol Next Generation (RIPng)',
    540: 'UUCP',
    554: 'Real Time Streaming Protocol (RTSP)',
    546: 'DHCPv6 Client',
    547: 'DHCPv6 Server',
    560: 'rmonitor',
    563: 'NNTP over SSL (NNTPS)',
    587: 'Email Message Submission (SMTP)',
    591: 'FileMaker 6.0 (HTTP Alternate)',
    593: 'Microsoft DCOM',
    631: 'Internet Printing Protocol (IPP)',
    636: 'LDAP over SSL (LDAPS)',
    873: 'rsync',
    902: 'VMware Server',
    989: 'FTP Data over TLS/SSL',
    990: 'FTP Control over TLS/SSL',
    993: 'IMAP over SSL (IMAPS)',
    995: 'POP3 over SSL (POP3S)',
    1080: 'SOCKS Proxy',
    1194: 'OpenVPN',
    1433: 'Microsoft SQL Server',
    1434: 'Microsoft SQL Monitor',
    1512: 'WINS',
    1723: 'Point-to-Point Tunneling Protocol (PPTP)',
    1812: 'RADIUS Authentication',
    1813: 'RADIUS Accounting',
    1863: 'Microsoft Notification Protocol (MSNP)',
    2049: 'Network File System (NFS)',
    2082: 'cPanel',
    2083: 'cPanel Secure',
    2086: 'WebHost Manager',
    2087: 'WebHost Manager Secure',
    2095: 'Webmail',
    2096: 'Webmail Secure',
    2181: 'Apache ZooKeeper',
    3306: 'MySQL',
    3389: 'Microsoft Terminal Server (RDP)',
    5432: 'PostgreSQL',
    5900: 'Virtual Network Computing (VNC)',
    5984: 'CouchDB',
    6379: 'Redis',
    6667: 'IRC (Internet Relay Chat)',
    6697: 'IRC over SSL (IRCS)',
    8000: 'Commonly used for web servers',
    8080: 'HTTP Alternate (HTTP Proxy)',
    8443: 'HTTPS Alternate',
    9000: 'Commonly used for web applications',
    9090: 'Commonly used for web applications',
    9200: 'Elasticsearch',
    9300: 'Elasticsearch',
    10000: 'Webmin',
    11211: 'Memcached',
    27017: 'MongoDB',
    31337: 'Back Orifice',
    32768: 'Network File System (NFS)',
}